<?php

namespace Database\Seeders;

use App\Models\Acuerdos;
use Illuminate\Database\Seeder;

class AcuerdosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $acuerdo_ab = new Acuerdos();
        $acuerdo_ab->titulo = "ACUERDO SOBRE SERVICIOS EN ARRENDAMIENTO DE INMUEBLE";
        $acuerdo_ab->cuerpo = "Entre {{ &#36;datos->name }} {{ &#36;datos->lastname }}identificación No. _______________________ documento de identidad tipo _______, con facultades suficientes para tomar decisiones sobre el arrendamiento del inmueble identificado en este documento, quien en adelante se denominará EL PROPIETARIO O SU REPRESENTANTE, y de otra parte ÉPICA CONSTRUCCIONES S.A. (ÉPICA INMOBILIARIA®) sociedad debidamente constituida con domicilio principal en la ciudad de Bogotá, NIT. 900.203.640-0 quien en adelante se denominará LA INMOBILIARIA, celebran por medio de este documento un acuerdo de SERVICIOS EN ARRENDAMIENTO sobre el inmueble en las condiciones que a continuación se describen: 
            PRIMERA. Objeto del acuerdo: EL PROPIETARIO O SU REPRESENTANTE contrata a LA INMOBILIARIA para que oferte al público el bien inmueble identificado así: DIRECCIÓN ____________________________________________ CIUDAD O MUNICIPIO ___________________ FOLIO DE MATRÍCULA ______________________, CHIP _______________________, con las características que se registran en ficha técnica anexa a este documento. PRECIO DE PUBLICACIÓN: &#36;____________________________________ incluida la cuota de administración si aplicara.
            SEGUNDA. Facultades de LA INMOBILIARIA: En desarrollo del presente acuerdo LA INMOBILIARIA desplegará las actividades que considere convenientes para lograr el arrendamiento del inmueble descrito, de manera independiente, sin subordinación o dependencia, utilizando sus propios medios, elementos de trabajo y personal a su cargo.
            TERCERA. Obligaciones de LA INMOBILIARIA:  LA INMOBILIARIA se obliga a: 1. Ofrecer el bien inmueble en el valor autorizado por EL PROPIETARIO O SU REPRESENTANTE e informar sobre propuestas de interesados en el inmueble. 2. Promover comercialmente el inmueble y/o realizar la administración del arrendamiento. 3. Una vez arrendado el inmueble, pagar a EL PROPIETARIO O SU REPRESENTANTE el día 05 del mes siguiente a la causación del arrendamiento los cánones.
            CUARTA. Obligaciones de EL PROPIETARIO O SU REPRESENTANTE: EL PROPIETARIO O SU REPRESENTANTE se obliga a: 1. Una vez arrendado el inmueble por la gestión de LA INMOBILIARIA, pagar a esta los valores correspondientes en relación con el arrendamiento del inmueble de que trata este acuerdo. 2. Facilitar a LA INMOBILIARIA el acceso al inmueble para que pueda exhibirlo en tiempos de respuesta ágiles ante posibles interesados. 3. Facilitar la documentación e información necesaria y real sobre el inmueble propuesto para el arrendamiento. 4. No desconocer los servicios o transacciones inmobiliarias a las que acceda EL PROPIETARIO O SU REPRESENTANTE por gestión de LA INMOBILIARIA. 5. EL PROPIETARIO O SU REPRESENTANTE autoriza desde ya a LA INMOBILIARIA a realizar aseo al inmueble cuando encuentre un arrendatario y previo a la entrega con cargo a EL PROPIETARIO O SU REPRESENTANTE por valor de $40.000 + IVA cuando se trate de un inmueble para vivienda hasta de 100 m² y $60.000 + IVA cuando se trate de un inmueble para vivienda superior a 100 m². Cuando se trate de un inmueble diferente a uso de vivienda se enviará previamente cotización de acuerdo con lo necesario para realizar dicho aseo.
            QUINTA. Publicidad: EL PROPIETARIO O SU REPRESENTANTE autoriza a LA INMOBILIARIA a realizar publicidad en internet que considere conveniente LA INMOBILIARIA, y se encuentra incluida en los servicios pactados, durará mientras el inmueble sea comercializado por LA INMOBILIARIA. La publicidad en medios diferentes a los antes mencionados y en caso de requerirse se acordará con EL PROPIETARIO O SU REPRESENTANTE y este asumirá dicho valor. EL PROPIETARIO O SU REPRESENTANTE suministrará las fotografías del inmueble a LA INMOBILIARIA y estas pasarán a ser propiedad de LA INMOBILIARIA, aún así LA INMOBILIARIA podrá abstenerse del uso de las mismas si considera que no cumplen con los estándares requeridos. EL PROPIETARIO O SU REPRESENTANTE se abstendrá de utilizar los elementos y/o  herramientas empleadas por LA INMOBILIARIA para realizar publicidad. EL PROPIETARIO O SU REPRESENTANTE se compromete a que en caso de comercializar el inmueble directamente o a través de la gestión realizada por terceros diferentes a LA INMOBILIARIA, todos realizarán la comercialización en los mismos términos de precio y características.
            SEXTA. Vigencia del acuerdo: Este acuerdo tiene una vigencia de tres (3) meses, contados a partir de su firma, prorrogables por treinta (30) días sucesivos automáticamente a menos que cualquiera de las partes desee darlo por terminado, para lo cual bastará una comunicación escrita dirigida a la otra parte.
            SÉPTIMA. Durante la vigencia del contrato de arrendamiento, EL PROPIETARIO O SU REPRESENTANTE reconocerá a LA INMOBILIARIA el 8% + IVA del canon de arrendamiento + cuota de administración de P.H. si aplica pagado mensualmente. Normas de interpretación. Para todos los efectos no previstos en este acuerdo se aplicarán las normas del Código de Comercio en especial al artículo 1340 y siguientes.
            OCTAVA. EL PROPIETARIO O SU REPRESENTANTE autoriza desde ya la recolección documental por parte de LA INMOBILIARIA al arrendatario que aplique a través de esta y a firmar contrato de arrendamiento cuando el estudio de arrendamiento de quien aplique sea aprobado. Por tratarse de un contrato consensual y sin perjuicio de la ejecución del presente acuerdo, en caso que EL PROPIETARIO O SU REPRESENTANTE se retracte por cualquier motivo y no haya dado aviso a LA INMOBILIARIA a través del correo electrónico acomercial@epicainmobiliaria.com.co antes de que LA INMOBILIARIA haya recibido documentos por parte del prospecto arrendatario, EL PROPIETARIO O SU REPRESENTANTE se obliga a pagar la suma equivalente a un (1) canon de arrendamiento a LA INMOBILIARIA. Sin perjuicio de lo anterior, EL PROPIETARIO O SU REPRESENTANTE además asumirá la devolución del dinero pagado por el arrendatario por concepto de estudio de arrendamiento y se hará responsable de dicho retracto y las sumas de dinero en caso que una o varias entidades competentes condenen el retracto conforme a la legislación colombiana. EL PROPIETARIO O SU REPRESENTANTE no podrá responsabilizar a LA INMOBILIARIA en caso que el retracto sea decisión del arrendatario.
            NOVENA Mérito ejecutivo. Este acuerdo presta mérito ejecutivo para el cobro por los servicios inmobiliarios prestados por LA INMOBILIARIA y a los que tiene derecho esta en caso que haya logrado efectivamente el arrendamiento del bien inmueble (incluso si se tratara de la simple presentación del cliente y/o este llegase a EL PROPIETARIO O SU REPRESENTANTE a través de cualquier mecanismo o herramienta empleada por LA INMOBILIARIA) y EL PROPIETARIO O SU REPRESENTANTE se niegue a pagarlos. Sin perjuicio de la ejecución del presente acuerdo, LA INMOBILIARIA se encontrará facultada para reportar un eventual incumplimiento de EL PROPIETARIO O SU REPRESENTANTE ante cualquier operador de información financiera legalmente establecido de conformidad con las leyes de la República de Colombia. Sin perjuicio de la ejecución del presente acuerdo, en caso de desistimiento por parte de EL PROPIETARIO O SU REPRESENTANTE dentro del término inicial de tres (3) meses en la comercialización del inmueble, este reconocerá a LA INMOBILIARIA la suma de $50.000 + IVA. En dicho caso, estará a cargo de EL PROPIETARIO O SU REPRESENTANTE recoger la(s) llave(s) en la dirección de LA INMOBILIARIA si esta la(s) tuviere. El correo electrónico de notificación de EL PROPIETARIO O SU REPRESENTANTE es _______________________________________ y el número de teléfono celular de EL PROPIETARIO O SU REPRESENTANTE es _________________________.
            DÉCIMA. Cláusula compromisoria. En caso de conflicto entre las partes, relativo a este acuerdo, su ejecución y liquidación, deberá agotarse en una diligencia de conciliación ante cualquier entidad autorizada para efectuarla, la cual será pagada por partes iguales.
            
            En señal de aprobación y plena validez del presente documento firmo electrónicamente de acuerdo con la Ley 527 de 1999 y el Decreto 2364 de 2012 en calidad de PROPIETARIO O SU REPRESENTANTE.";
        $acuerdo_ab->plan = 1;
        $acuerdo_ab->tipo_negocio = 2;
        $acuerdo_ab->save();

        $acuerdo_ae = new Acuerdos();
        $acuerdo_ae->titulo = "ACUERDO SOBRE SERVICIOS EN ARRENDAMIENTO DE INMUEBLE";
        $acuerdo_ae->cuerpo = "Entre ______________________________________________________ identificación No. _______________________ documento de identidad tipo _______, con facultades suficientes para tomar decisiones sobre el arrendamiento del inmueble identificado en este documento, quien en adelante se denominará EL PROPIETARIO O SU REPRESENTANTE, y de otra parte ÉPICA CONSTRUCCIONES S.A. (ÉPICA INMOBILIARIA®) sociedad debidamente constituida con domicilio principal en la ciudad de Bogotá, NIT. 900.203.640-0 quien en adelante se denominará LA INMOBILIARIA, celebran por medio de este documento un acuerdo de SERVICIOS EN ARRENDAMIENTO sobre el inmueble en las condiciones que a continuación se describen: 
            PRIMERA. Objeto del acuerdo: EL PROPIETARIO O SU REPRESENTANTE contrata a LA INMOBILIARIA para que oferte al público el bien inmueble identificado así: DIRECCIÓN ____________________________________________ CIUDAD O MUNICIPIO ___________________ FOLIO DE MATRÍCULA ______________________, CHIP _______________________, con las características que se registran en ficha técnica anexa a este documento. PRECIO DE PUBLICACIÓN: ____________________________________ incluida la cuota de administración si aplicara.
            SEGUNDA. Facultades de LA INMOBILIARIA: En desarrollo del presente acuerdo LA INMOBILIARIA desplegará las actividades que considere convenientes para lograr el arrendamiento del inmueble descrito, de manera independiente, sin subordinación o dependencia, utilizando sus propios medios, elementos de trabajo y personal a su cargo.
            TERCERA. Obligaciones de LA INMOBILIARIA:  LA INMOBILIARIA se obliga a: 1. Ofrecer el bien inmueble en el valor autorizado por EL PROPIETARIO O SU REPRESENTANTE e informar sobre propuestas de interesados en el inmueble. 2. Enviar informe periódico de la gestión comercial realizada. 3. Promover comercialmente el inmueble y/o realizar la administración del arrendamiento. 4. Una vez arrendado el inmueble, pagar a EL PROPIETARIO O SU REPRESENTANTE el día 05 del mes siguiente a la causación del arrendamiento los cánones.
            CUARTA. Obligaciones de EL PROPIETARIO O SU REPRESENTANTE: EL PROPIETARIO O SU REPRESENTANTE se obliga a: 1. Una vez arrendado el inmueble por la gestión de LA INMOBILIARIA, pagar a esta los valores correspondientes en relación con el arrendamiento del inmueble de que trata este acuerdo. 2. Facilitar a LA INMOBILIARIA el acceso al inmueble para que pueda exhibirlo en tiempos de respuesta ágiles ante posibles interesados. 3. Facilitar la documentación e información necesaria y real sobre el inmueble propuesto para el arrendamiento. 4. No desconocer los servicios o transacciones inmobiliarias a las que acceda EL PROPIETARIO O SU REPRESENTANTE por gestión de LA INMOBILIARIA. 5. EL PROPIETARIO O SU REPRESENTANTE autoriza desde ya a LA INMOBILIARIA a realizar aseo al inmueble cuando encuentre un arrendatario y previo a la entrega con cargo a EL PROPIETARIO O SU REPRESENTANTE por valor de $40.000 + IVA cuando se trate de un inmueble para vivienda hasta de 100 m² y $60.000 + IVA cuando se trate de un inmueble para vivienda superior a 100 m². Cuando se trate de un inmueble diferente a uso de vivienda se enviará previamente cotización de acuerdo con lo necesario para realizar dicho aseo.
            QUINTA. Publicidad: EL PROPIETARIO O SU REPRESENTANTE autoriza a LA INMOBILIARIA a realizar publicidad en internet que considere conveniente LA INMOBILIARIA, y se encuentra incluida en los servicios pactados, durará mientras el inmueble sea comercializado por LA INMOBILIARIA. La publicidad en medios diferentes a los antes mencionados y en caso de requerirse se acordará con EL PROPIETARIO O SU REPRESENTANTE y este asumirá dicho valor. EL PROPIETARIO O SU REPRESENTANTE no utilizará, bajo ningún propósito, las fotografías de LA INMOBILIARIA o cualquier otro elemento y/o herramienta publicitaria de la misma y reconoce que estas son propiedad de LA INMOBILIARIA, aún cuando estas hayan sido suministradas por EL PROPIETARIO O SU REPRESENTANTE. En beneficio de la gestión adecuada de publicidad, EL PROPIETARIO O SU REPRESENTANTE acepta que únicamente se fijarán avisos en ventana de LA INMOBILIARIA, en caso que EL PROPIETARIO O SU REPRESENTANTE directamente o a través de terceros fije avisos en ventana, LA INMOBILIARIA se abstendrá de utilizar los suyos. EL PROPIETARIO O SU REPRESENTANTE se compromete a que en caso de comercializar el inmueble directamente o a través de la gestión realizada por terceros diferentes a LA INMOBILIARIA, todos realizarán la comercialización en los mismos términos de precio y características.
            SEXTA. Vigencia del acuerdo: Este acuerdo tiene una vigencia de tres (3) meses, contados a partir de su firma, prorrogables por treinta (30) días sucesivos automáticamente a menos que cualquiera de las partes desee darlo por terminado, para lo cual bastará una comunicación escrita dirigida a la otra parte.
            SÉPTIMA. Durante la vigencia del contrato de arrendamiento, EL PROPIETARIO O SU REPRESENTANTE reconocerá a LA INMOBILIARIA el 10% + IVA del canon de arrendamiento + cuota de administración de P.H. si aplica pagado mensualmente. Normas de interpretación. Para todos los efectos no previstos en este acuerdo se aplicarán las normas del Código de Comercio en especial al artículo 1340 y siguientes.
            OCTAVA. EL PROPIETARIO O SU REPRESENTANTE autoriza desde ya la recolección documental por parte de LA INMOBILIARIA al arrendatario que aplique a través de esta y a firmar contrato de arrendamiento cuando el estudio de arrendamiento de quien aplique sea aprobado. Por tratarse de un contrato consensual y sin perjuicio de la ejecución del presente acuerdo, en caso que EL PROPIETARIO O SU REPRESENTANTE se retracte por cualquier motivo y no haya dado aviso a LA INMOBILIARIA a través del correo electrónico acomercial@epicainmobiliaria.com.co antes de que LA INMOBILIARIA haya recibido documentos por parte del prospecto arrendatario, EL PROPIETARIO O SU REPRESENTANTE se obliga a pagar la suma equivalente a un (1) canon de arrendamiento a LA INMOBILIARIA. Sin perjuicio de lo anterior, EL PROPIETARIO O SU REPRESENTANTE además asumirá la devolución del dinero pagado por el arrendatario por concepto de estudio de arrendamiento y se hará responsable de dicho retracto y las sumas de dinero en caso que una o varias entidades competentes condenen el retracto conforme a la legislación colombiana. EL PROPIETARIO O SU REPRESENTANTE no podrá responsabilizar a LA INMOBILIARIA en caso que el retracto sea decisión del arrendatario.
            NOVENA. Mérito ejecutivo. Este acuerdo presta mérito ejecutivo para el cobro por los servicios inmobiliarios prestados por LA INMOBILIARIA y a los que tiene derecho esta en caso que haya logrado efectivamente el arrendamiento del bien inmueble (incluso si se tratara de la simple presentación del cliente y/o este llegase a EL PROPIETARIO O SU REPRESENTANTE a través de cualquier mecanismo o herramienta empleada por LA INMOBILIARIA) y EL PROPIETARIO O SU REPRESENTANTE se niegue a pagarlos. Sin perjuicio de la ejecución del presente acuerdo, LA INMOBILIARIA se encontrará facultada para reportar un eventual incumplimiento de EL PROPIETARIO O SU REPRESENTANTE ante cualquier operador de información financiera legalmente establecido de conformidad con las leyes de la República de Colombia. Sin perjuicio de la ejecución del presente acuerdo, en caso de desistimiento por parte de EL PROPIETARIO O SU REPRESENTANTE dentro del término inicial de tres (3) meses en la comercialización del inmueble, este reconocerá a LA INMOBILIARIA la suma de $50.000 + IVA. En dicho caso, estará a cargo de EL PROPIETARIO O SU REPRESENTANTE recoger la(s) llave(s) en la dirección de LA INMOBILIARIA si esta la(s) tuviere.  El correo electrónico de notificación de EL PROPIETARIO O SU REPRESENTANTE es _______________________________________ y el número de teléfono celular de EL PROPIETARIO O SU REPRESENTANTE es _________________________.
            DÉCIMA. Cláusula compromisoria. En caso de conflicto entre las partes, relativo a este acuerdo, su ejecución y liquidación, deberá agotarse en una diligencia de conciliación ante cualquier entidad autorizada para efectuarla, la cual será pagada por partes iguales.
            
            En señal de aprobación y plena validez del presente documento firmo electrónicamente de acuerdo con la Ley 527 de 1999 y el Decreto 2364 de 2012 en calidad de PROPIETARIO O SU REPRESENTANTE.";
        $acuerdo_ae->plan = 2;
        $acuerdo_ae->tipo_negocio = 2;
        $acuerdo_ae->save();

        $acuerdo_ap = new Acuerdos();
        $acuerdo_ap->titulo = "ACUERDO SOBRE SERVICIOS EN ARRENDAMIENTO DE INMUEBLE";
        $acuerdo_ap->cuerpo = "Entre ______________________________________________________ identificación No. _______________________ documento de identidad tipo _______, con facultades suficientes para tomar decisiones sobre el arrendamiento del inmueble identificado en este documento, quien en adelante se denominará EL PROPIETARIO O SU REPRESENTANTE, y de otra parte ÉPICA CONSTRUCCIONES S.A. (ÉPICA INMOBILIARIA®) sociedad debidamente constituida con domicilio principal en la ciudad de Bogotá, NIT. 900.203.640-0 quien en adelante se denominará LA INMOBILIARIA, celebran por medio de este documento un acuerdo de SERVICIOS EN ARRENDAMIENTO sobre el inmueble en las condiciones que a continuación se describen: 
            PRIMERA. Objeto del acuerdo: EL PROPIETARIO O SU REPRESENTANTE contrata a LA INMOBILIARIA para que oferte al público el bien inmueble identificado así: DIRECCIÓN ____________________________________________ CIUDAD O MUNICIPIO ___________________ FOLIO DE MATRÍCULA ______________________, CHIP _______________________, con las características que se registran en ficha técnica anexa a este documento. PRECIO DE PUBLICACIÓN: ____________________________________ incluida la cuota de administración si aplicara.
            SEGUNDA. Facultades de LA INMOBILIARIA: En desarrollo del presente acuerdo LA INMOBILIARIA desplegará las actividades que considere convenientes para lograr el arrendamiento del inmueble descrito, de manera independiente, sin subordinación o dependencia, utilizando sus propios medios, elementos de trabajo y personal a su cargo.
            TERCERA. Obligaciones de LA INMOBILIARIA:  LA INMOBILIARIA se obliga a: 1. Ofrecer el bien inmueble en el valor autorizado por EL PROPIETARIO O SU REPRESENTANTE e informar sobre propuestas de interesados en el inmueble. 2. Enviar informe periódico de la gestión comercial realizada. 3. Promover comercialmente el inmueble y/o realizar la administración del arrendamiento. 4. Una vez arrendado el inmueble, pagar a EL PROPIETARIO O SU REPRESENTANTE el día 05 del mes siguiente a la causación del arrendamiento los cánones.
            CUARTA. Obligaciones de EL PROPIETARIO O SU REPRESENTANTE: EL PROPIETARIO O SU REPRESENTANTE se obliga a: 1. Una vez arrendado el inmueble por la gestión de LA INMOBILIARIA, pagar a esta los valores correspondientes en relación con el arrendamiento del inmueble de que trata este acuerdo. 2. Facilitar a LA INMOBILIARIA el acceso al inmueble para que pueda exhibirlo en tiempos de respuesta ágiles ante posibles interesados. 3. Facilitar la documentación e información necesaria y real sobre el inmueble propuesto para el arrendamiento. 4. No desconocer los servicios o transacciones inmobiliarias a las que acceda EL PROPIETARIO O SU REPRESENTANTE por gestión de LA INMOBILIARIA. 5. EL PROPIETARIO O SU REPRESENTANTE autoriza desde ya a LA INMOBILIARIA a realizar aseo al inmueble cuando encuentre un arrendatario y previo a la entrega con cargo a EL PROPIETARIO O SU REPRESENTANTE por valor de $40.000 + IVA cuando se trate de un inmueble para vivienda hasta de 100 m² y $60.000 + IVA cuando se trate de un inmueble para vivienda superior a 100 m². Cuando se trate de un inmueble diferente a uso de vivienda se enviará previamente cotización de acuerdo con lo necesario para realizar dicho aseo.
            QUINTA. Publicidad: EL PROPIETARIO O SU REPRESENTANTE autoriza a LA INMOBILIARIA a realizar publicidad en internet que considere conveniente LA INMOBILIARIA, y se encuentra incluida en los servicios pactados, durará mientras el inmueble sea comercializado por LA INMOBILIARIA. La publicidad en medios diferentes a los antes mencionados y en caso de requerirse se acordará con EL PROPIETARIO O SU REPRESENTANTE y este asumirá dicho valor. EL PROPIETARIO O SU REPRESENTANTE no utilizará, bajo ningún propósito, las fotografías de LA INMOBILIARIA o cualquier otro elemento y/o herramienta publicitaria de la misma y reconoce que estas son propiedad de LA INMOBILIARIA, aún cuando estas hayan sido suministradas por EL PROPIETARIO O SU REPRESENTANTE. En beneficio de la gestión adecuada de publicidad, EL PROPIETARIO O SU REPRESENTANTE acepta que únicamente se fijarán avisos en ventana de LA INMOBILIARIA, en caso que EL PROPIETARIO O SU REPRESENTANTE directamente o a través de terceros fije avisos en ventana, LA INMOBILIARIA se abstendrá de utilizar los suyos. EL PROPIETARIO O SU REPRESENTANTE se compromete a que en caso de comercializar el inmueble directamente o a través de la gestión realizada por terceros diferentes a LA INMOBILIARIA, todos realizarán la comercialización en los mismos términos de precio y características.
            SEXTA. Vigencia del acuerdo: Este acuerdo tiene una vigencia de tres (3) meses, contados a partir de su firma, prorrogables por treinta (30) días sucesivos automáticamente a menos que cualquiera de las partes desee darlo por terminado, para lo cual bastará una comunicación escrita dirigida a la otra parte.
            SÉPTIMA. Durante la vigencia del contrato de arrendamiento, EL PROPIETARIO O SU REPRESENTANTE reconocerá a LA INMOBILIARIA el 12% + IVA del canon de arrendamiento + cuota de administración de P.H. si aplica pagado mensualmente. Normas de interpretación. Para todos los efectos no previstos en este acuerdo se aplicarán las normas del Código de Comercio en especial al artículo 1340 y siguientes.
            OCTAVA. EL PROPIETARIO O SU REPRESENTANTE autoriza desde ya la recolección documental por parte de LA INMOBILIARIA al arrendatario que aplique a través de esta y a firmar contrato de arrendamiento cuando el estudio de arrendamiento de quien aplique sea aprobado. Por tratarse de un contrato consensual y sin perjuicio de la ejecución del presente acuerdo, en caso que EL PROPIETARIO O SU REPRESENTANTE se retracte por cualquier motivo y no haya dado aviso a LA INMOBILIARIA a través del correo electrónico acomercial@epicainmobiliaria.com.co antes de que LA INMOBILIARIA haya recibido documentos por parte del prospecto arrendatario, EL PROPIETARIO O SU REPRESENTANTE se obliga a pagar la suma equivalente a un (1) canon de arrendamiento a LA INMOBILIARIA. Sin perjuicio de lo anterior, EL PROPIETARIO O SU REPRESENTANTE además asumirá la devolución del dinero pagado por el arrendatario por concepto de estudio de arrendamiento y se hará responsable de dicho retracto y las sumas de dinero en caso que una o varias entidades competentes condenen el retracto conforme a la legislación colombiana. EL PROPIETARIO O SU REPRESENTANTE no podrá responsabilizar a LA INMOBILIARIA en caso que el retracto sea decisión del arrendatario.
            NOVENA. Mérito ejecutivo. Este acuerdo presta mérito ejecutivo para el cobro por los servicios inmobiliarios prestados por LA INMOBILIARIA y a los que tiene derecho esta en caso que haya logrado efectivamente el arrendamiento del bien inmueble (incluso si se tratara de la simple presentación del cliente y/o este llegase a EL PROPIETARIO O SU REPRESENTANTE a través de cualquier mecanismo o herramienta empleada por LA INMOBILIARIA) y EL PROPIETARIO O SU REPRESENTANTE se niegue a pagarlos. Sin perjuicio de la ejecución del presente acuerdo, LA INMOBILIARIA se encontrará facultada para reportar un eventual incumplimiento de EL PROPIETARIO O SU REPRESENTANTE ante cualquier operador de información financiera legalmente establecido de conformidad con las leyes de la República de Colombia. Sin perjuicio de la ejecución del presente acuerdo, en caso de desistimiento por parte de EL PROPIETARIO O SU REPRESENTANTE dentro del término inicial de tres (3) meses en la comercialización del inmueble, este reconocerá a LA INMOBILIARIA la suma de $50.000 + IVA. En dicho caso, estará a cargo de EL PROPIETARIO O SU REPRESENTANTE recoger la(s) llave(s) en la dirección de LA INMOBILIARIA si esta la(s) tuviere. El correo electrónico de notificación de EL PROPIETARIO O SU REPRESENTANTE es _______________________________________ y el número de teléfono celular de EL PROPIETARIO O SU REPRESENTANTE es _________________________.
            DÉCIMA. Cláusula compromisoria. En caso de conflicto entre las partes, relativo a este acuerdo, su ejecución y liquidación, deberá agotarse en una diligencia de conciliación ante cualquier entidad autorizada para efectuarla, la cual será pagada por partes iguales.
            
            En señal de aprobación y plena validez del presente documento firmo electrónicamente de acuerdo con la Ley 527 de 1999 y el Decreto 2364 de 2012 en calidad de PROPIETARIO O SU REPRESENTANTE.";
        $acuerdo_ap->plan = 3;
        $acuerdo_ap->tipo_negocio = 2;
        $acuerdo_ap->save();
    }
}
